 // List from https://github.com/opencovid19-fr/data/tree/master/agences-regionales-sante
 module.exports = [
  'auvergne-rhone-alpes',
  'bourgogne-franche-comte',
  'bretagne',
  'centre-val-de-loire',
  'corse',
  'grand-est',
  'guadeloupe',
  'guyane',
  'hauts-de-france',
  'ile-de-france',
  'martinique',
  'mayotte',
  'normandie',
  'nouvelle-aquitaine',
  'nouvelle-caledonie',
  'occitanie',
  'pays-de-la-loire',
  'polynesie-francaise',
  'provence-alpes-cote-dazur',
  'reunion',
  'saint-barthelemy',
  'saint-martin',
  'wallis-et-futuna'
]
